### ISSUE TITLE
Null return type required

### ISSUE THREAD

**Issue by Samistine** [tebru/gson-php#10]
On getter functions I have to allow nulls in the type declaration ?MySpecialClass. I tried specifying the type using annotations but the getter still gets called before there is data in the variable it's calling.

    /**
     * @return string
     */
    public function getNumber(): ?string
    {
        return $this->number;
    }

I would like to do this

    /**
     * @return string
     */
    public function getNumber(): string
    {
        return $this->number;
    }

**Comment by natebrunette** [comment]
@Samistine this is happening because gson allows you to pass in an object to deserialize into. In order to handle nested objects, it needs to try to fetch the real object if it exists. I'll look into a way to avoid this if the property is null.

**Comment by natebrunette** [comment]
Resolved with b27dd775d6f249cdcb7646a963d0f3e695713b54. Tag coming soon.
