### ISSUE TITLE
symfony/cache deprecation of SimpleCacheAdapter

### ISSUE THREAD

**Issue by ericmillsio** [tebru/gson-php#42]
Fatal error: Interface 'Psr\SimpleCache\CacheInterface' not found in /Users/ericmills/MailControl/tracking-api/vendor/symfony/cache/Simple/ArrayCache.php on line 28

deprecated SimpleCacheAdapter, use Psr16Adapter instead. This is withing symfony/cache 4.3.0 it was deprecated.
https://github.com/symfony/cache/blob/master/CHANGELOG.md

**Comment by natebrunette** [comment]
I have a branch open here: https://github.com/tebru/gson-php/pull/43

Could you verify adding this dependency fixes the issue with symfony 4.3?

**Comment by natebrunette** [comment]
merged #43
