### ISSUE TITLE
Function ReflectionType::__toString() is deprecated

### ISSUE THREAD

**Issue by moto-cinemarket** [tebru/gson-php#47]
I'm trying to use gson-php: 0.7.1 and I'm receiving this error due to __toString is deprecated as of php 7.1

this error is thrown in TypeTokenFactory in line 98
`$setterType = TypeToken::create((string)$parameter->getType());`

though instead of casting to string `getName()` should be called.

**Comment by natebrunette** [comment]
Thanks, I have the change made already, but I didn't realize it was urgent. I'll get that pushed up and released sometime today.

**Comment by moto-cinemarket** [comment]
Well done! couldn't received better reply.

**Comment by natebrunette** [comment]
tagged v0.7.2

**Comment by moto-cinemarket** [comment]
Thank you :+1:
