### ISSUE TITLE
Consider migrating to the GitHub Action

### ISSUE THREAD

**Issue by peter279k** [tebru/gson-php#53]
As title, since the Travis CI building is very slow, I think it's time to migrate to the GitHub actions.

Once this issue has been accepted by repository owner, I will be happy to work on that.

**Comment by natebrunette** [comment]
The last build took about 4 minutes. I don't think that's an unreasonable amount of time. It doesn't get built that often.

**Comment by peter279k** [comment]
The latest building has been successful for about three months ago.

The slow building happens at the recent time.

**Comment by natebrunette** [comment]
Could you show me an example?

**Comment by peter279k** [comment]
Here is the [latest build](https://travis-ci.com/github/peter279k/gson-php/builds/205587226) on my forked repository recently.

It takes about 9 minutes.

I think this problem is not necessary and it may be a improved issue :).
